on:
  push:
    branches: [main]
  workflow_dispatch:

name: build-r-package

permissions:
  contents: write

jobs:
  build-r-package:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
# There are issues here finding and copying multiple files
    - name: Copy raw data
      run: |
        cp -u "$(find ~+/raw -type f | grep -v "yaml")" .R-package/inst/extdata
        
    - name: Commit built R package
      run: |
        git config --local user.name actions-user
        git config --global user.email 'actions@github.com'
        git add .
        git commit -am "[auto] Build R Package" || echo "No changes to commit"
        git push origin main

